const Recipes = {
  "Olive Oil Pasta": ["spaghetti", "olive oil"],
  "Garlic Rice": ["white rice", "garlic"],
  "Honey Butter Spread": ["butter", "honey"],
  "Garlic Bread": ["bread", "garlic"],
  "Vanilla Sugar Syrup": ["sugar", "vanilla"],
  "Spiced Olive Oil": ["olive oil", "paprika"],
  "Baked Potatoes": ["potato", "olive oil"],
  "Carrot Sticks with Honey": ["carrot", "honey"],
  "Tomato Salsa": ["tomato", "onion"],
  "Garlic Roasted Broccoli": ["broccoli", "garlic"],
  "Cucumber Salad": ["cucumber", "lime"],
  "Banana Smoothie": ["banana", "milk"],
  "Mango Pulp": ["mango", "sugar"],
  "Lemon Water": ["lemon", "water"],
  "Tamarind Chutney": ["tamarind", "jaggery"],
  "Coconut Lime Dressing": ["coconut", "lime"],
  "Cheese Toast": ["cheese", "bread"],
  "Paneer Butter": ["paneer", "butter"],
  "Curd Rice": ["curd", "white rice"],
  "Ghee Roti": ["ghee", "bread"],
  "Milk Tea": ["milk", "sugar"],
  "Honey Glaze": ["honey", "cinnamon"],
  "Jaggery Syrup": ["jaggery", "water"],
  "Chocolate Spread": ["chocolate syrup", "butter"],
  "Coconut Sweet": ["coconut", "sugar"],
  "Grilled Chicken": ["chicken breast", "olive oil"],
  "Egg Fry": ["egg", "butter"],
  "Fish Fry": ["salmon", "olive oil"],
  "Tuna Salad": ["tuna steak", "mayonnaise"],
  "Honey Lemon Tea": ["honey", "lemon"],
  "Potato Cheese Balls": ["potato", "cheese"],
  "Butter Garlic Sauce": ["butter", "garlic"],
  "Tomato Cream Dip": ["tomato", "cream"],
  "Ghee Rice": ["white rice", "ghee"],
  "Paneer Curry": ["paneer", "tomato"],
  "Lemon Rice": ["white rice", "lemon"],
  "Curd Chutney": ["curd", "cucumber"],
  "Garlic Dal": ["garlic", "white rice"],
  "Butter Roti": ["butter", "flour"],
  "Potato Fry": ["potato", "cumin"],
  "Tomato Dal": ["tomato", "white rice"],
  "Honey Roti": ["honey", "bread"],
  "Masala Rice": ["white rice", "paprika"],
  "Sweet Poha": ["jaggery", "coconut"],
  "Vegetable Stir Fry": ["bell pepper", "onion"],
  "Spicy Egg Curry": ["egg", "chili powder"],
  "Dal Butter Fry": ["butter", "white rice"],
  "Tomato Raita": ["tomato", "curd"],
  "Lime Pickle": ["lime", "salt"],
  "Carrot Halwa": ["carrot", "milk"],
  "Sweet Rice": ["white rice", "sugar"],
  "Paprika Potato": ["potato", "paprika"],
  "Coconut Rice": ["white rice", "coconut"],
  "Chili Paneer": ["paneer", "chili powder"],
  "Honey and Sugar Syrup": ["honey", "sugar"],
  "Molasses and Brown Sugar Drizzle": ["molasses", "brown sugar"],
  "Coconut Sugar Sweetener": ["coconut sugar", "sugar"],
  "Maple Syrup Glaze": ["maple syrup", "sugar"],
  "Stevia Sweetened Drink": ["stevia", "water"],
  "Brown Sugar Cinnamon Toast": ["brown sugar", "cinnamon", "butter"],
  "Honey and Vanilla Sweet Cream": ["honey", "cream", "vanilla sugar"],
  "Agave Nectar Fruit Salad": ["agave nectar", "orange", "apple"],
  "Sugar Syrup for Desserts": ["sugar", "water", "vanilla sugar"],
  "Caramelized Banana": ["banana", "caramel syrup", "butter"],
  "Chocolate Syrup Cake": ["chocolate syrup", "flour", "sugar", "butter", "eggs", "vanilla sugar"],
  "Maple Syrup Pancakes": ["maple syrup", "flour", "milk", "eggs", "butter", "baking powder"],
  "Molasses Ginger Cookies": ["molasses", "ginger", "flour", "butter", "sugar", "egg"],
  "Honey Lemon Glazed Chicken": ["honey", "lemon juice", "chicken breast", "garlic", "olive oil", "soy sauce"],
  "Caramel and Banana Smoothie": ["caramel syrup", "banana", "yogurt", "milk", "ice cream", "vanilla sugar"],
  "Agave Nectar Smoothie": ["agave nectar", "banana"],
  "Coconut Sugar Pudding": ["coconut sugar", "milk"],
  "Date Syrup Cake": ["date syrup", "flour"],
  "Stevia Sweetened Fruit Drink": ["stevia", "watermelon"],
  "Jaggery Lemon Drink": ["jaggery", "lemon juice"],
  "Cane Sugar Lemonade": ["cane sugar", "lemon", "water"],
  "Honey Ginger Drink": ["honey", "ginger", "water"],
  "Molasses Sweet Potatoes": ["molasses", "sweet potato", "butter"],
  "Caramel Apple Slices": ["caramel syrup", "apple", "cinnamon"],
  "Maple Syrup Cinnamon Rolls": ["maple syrup", "flour", "cinnamon"],
  "Chocolate Syrup Brownies": ["chocolate syrup", "flour", "butter", "sugar", "eggs", "vanilla sugar"],
  "Molasses Oatmeal Cookies": ["molasses", "oats", "butter", "sugar", "egg", "flour"],
  "Maple Syrup Granola": ["maple syrup", "oats", "almond", "coconut", "butter", "vanilla extract"],
  "Sugar Syrup Drizzled Pancakes": ["sugar syrup", "pancake", "butter", "syrup", "eggs", "flour"],
  "Honey Walnut Cake": ["honey", "walnuts", "flour", "eggs", "butter", "sugar"],
  "Agave Nectar Fruit Popsicles": ["agave nectar", "fruit"],
  "Molasses Glazed Chicken": ["molasses", "chicken"],
  "Coconut Sugar Smoothie": ["coconut sugar", "milk"],
  "Honey Butter Toast": ["honey", "butter"],
  "Maple Syrup Coffee": ["maple syrup", "coffee"],
  "Stevia Chocolate Cake": ["stevia", "flour", "butter"],
  "Brown Sugar Glazed Carrots": ["brown sugar", "carrot", "butter"],
  "Vanilla Sugar Pudding": ["vanilla sugar", "milk", "cornstarch"],
  "Molasses Honey Drizzle": ["molasses", "honey", "butter"],
  "Caramel Chocolate Cupcakes": ["caramel syrup", "chocolate syrup", "flour"],
  "Honey Almond Tart": ["honey", "almonds", "flour", "butter", "eggs", "sugar"],
  "Maple Syrup Chicken Wings": ["maple syrup", "chicken wings", "garlic", "soy sauce", "butter", "ginger"],
  "Brown Sugar Peach Cobbler": ["brown sugar", "peach", "flour", "butter", "sugar", "vanilla"],
  "Jaggery Carrot Halwa": ["jaggery", "carrot", "milk", "ghee", "cardamom", "nuts"],
  "Coconut Sugar Apple Pie": ["coconut sugar", "apple", "flour", "butter", "sugar", "cinnamon"],
  "Sweet Potato Mash": ["sweet potato", "butter"],
  "Chili Honey Dip": ["honey", "chili powder", "mayonnaise"],
  "Vanilla Cinnamon Toast": ["bread", "vanilla", "cinnamon"],
  "Soy Butter Chicken": ["chicken breast", "soy sauce", "butter"],
  "Garlic Butter Chicken": ["chicken breast", "butter", "garlic"],
  "Honey Mustard Chicken": ["chicken breast", "honey", "mustard"],
  "Lemon Garlic Shrimp": ["shrimp", "garlic", "lemon"],
  "Tomato Basil Soup": ["tomato", "basil", "garlic"],
  "Potato Salad": ["potato", "mayonnaise", "mustard"],
  "Pineapple Chicken": ["chicken breast", "pineapple", "soy sauce"],
  "Paneer Tikka": ["paneer", "yogurt", "chili powder"],
  "Egg Salad": ["egg", "mayonnaise", "mustard"],
  "Spaghetti with Garlic and Oil": ["spaghetti", "olive oil", "garlic"],
  "Fruit Salad": ["banana", "apple", "orange"],
  "Honey Mustard Dressing": ["honey", "mustard", "olive oil"],
  "Garlic Butter Toast": ["bread", "butter", "garlic"],
  "Tomato Basil Pasta": ["spaghetti", "tomato", "basil"],
  "Sweet Potato Fries": ["sweet potato", "olive oil", "paprika"],
  "Simple Guacamole": ["avocado", "tomato", "onion"],
  "Crispy Potatoes": ["potato", "olive oil", "paprika"],
  "Garlic Butter Pasta": ["spaghetti", "butter", "garlic"],
  "Tomato Soup": ["tomato", "onion", "garlic"],
  "Spicy Grilled Chicken": ["chicken breast", "chili powder", "vegetable oil"],
  "Cheese Omelette": ["egg", "cheddar", "butter"],
  "Potato Wedges": ["potato", "olive oil", "paprika"],
  "Fried Egg Sandwich": ["bread", "egg", "butter"],
  "Carrot Soup": ["carrot", "onion", "vegetable oil"],
  "Fruit Smoothie": ["banana", "milk", "honey"],
  "Lemon Garlic Chicken": ["chicken breast", "garlic", "lemon juice"],
  "Cabbage Stir Fry": ["cabbage", "onion", "vegetable oil"],
  "Baked Salmon": ["salmon", "olive oil", "lemon juice"],
  "Spinach Salad": ["spinach", "olive oil", "lemon juice"],
  "Garlic Butter Shrimp": ["shrimp", "butter", "garlic"],
  "Pineapple Salad": ["pineapple", "coconut", "lime juice"],
  "Potato Curry": ["potato", "onion", "cumin"],
  "Fruit Chaat": ["apple", "orange", "lemon juice"],
  "Egg Curry": ["egg", "onion", "tomato"],
  "Broccoli Stir Fry": ["broccoli", "garlic", "olive oil"],
  "Yogurt Parfait": ["yogurt", "honey", "blueberry"],
  "Spicy Prawns": ["prawns", "chili powder", "garlic"],
  "Lemonade": ["lemon", "sugar", "water"],
  "Apple Smoothie": ["apple", "milk", "honey"],
  "Grilled Vegetables": ["bell pepper", "onion", "zucchini"],
  "Tomato Basil Salad": ["tomato", "basil", "olive oil"],
  "Cheese Stuffed Mushrooms": ["mushrooms", "cheddar", "cream cheese"],
  "Aloo Gobi": ["potato", "cauliflower", "onion", "cumin"],
  "Chicken Curry": ["chicken breast", "onion", "tomato", "cumin"],
  "Chana Masala": ["chickpeas", "onion", "tomato", "garlic"],
  "Paneer Butter Masala": ["paneer", "butter", "tomato", "cream"],
  "Egg Bhurji": ["egg", "onion", "tomato", "garlic"],
  "Prawn Masala": ["prawns", "onion", "tomato", "cumin"],
  "Vegetable Biryani": ["rice", "carrot", "onion", "cumin"],
  "Dal Tadka": ["lentils", "onion", "garlic", "cumin"],
  "Aloo Keema": ["potato", "ground chicken", "onion", "garlic"],
  "Cucumber Raita": ["yogurt", "cucumber", "garlic", "salt"],
  "Mango Lassi": ["mango", "yogurt", "sugar", "milk"],
  "Dahi Puri": ["puri", "yogurt", "onion", "tamarind chutney"],
  "Chana Chaat": ["chickpeas", "onion", "tomato", "lemon juice"],
  "Cabbage Paratha": ["flour", "cabbage", "onion", "cumin"],
  "Baingan Bharta": ["eggplant", "onion", "tomato", "garlic"],
  "Tandoori Chicken": ["chicken", "yogurt", "garlic", "chili powder"],
  "Gajar Halwa": ["carrot", "milk", "sugar", "cardamom"],
  "Lassi": ["yogurt", "water", "sugar", "cardamom"],
  "Aloo Methi": ["potato", "fenugreek", "onion", "cumin"],
  "Shahi Paneer": ["paneer", "cream", "onion", "tomato"],
  "Aloo Tikki": ["potato", "onion", "garlic", "chili powder"],
  "Tandoori Prawns": ["prawns", "yogurt", "garlic", "chili powder"],
  "Methi Thepla": ["flour", "fenugreek", "carrot", "cumin"],
  "Kadhi Pakora": ["yogurt", "flour", "onion", "garlic"],
  "Bhindi Masala": ["okra", "onion", "tomato", "cumin"],
  "Tomato Egg Curry": ["egg", "onion", "tomato", "cumin"],
  "Kachumber Salad": ["cucumber", "tomato", "onion", "lemon juice"],
  "Aloo Baingan": ["potato", "eggplant", "onion", "cumin"],
  "Gobi Paratha": ["flour", "cauliflower", "onion", "cumin"],
  "Pesarattu": ["green gram", "onion", "green chili", "cumin"],
  "Chickpea Salad": ["chickpeas", "onion", "tomato", "lemon juice"],
  "Mango Chutney": ["mango", "sugar", "vinegar", "garlic"],
  "Pineapple Raita": ["pineapple", "yogurt", "onion", "cumin"],
  "Dhokla": ["flour", "yogurt", "mustard", "cumin"],
  "Stuffed Paneer": ["paneer", "tomato", "onion", "garlic"],
  "Chana Pulao": ["chickpeas", "rice", "onion", "cumin"],
  "Kadhi": ["yogurt", "onion", "garlic", "cumin"],
  "Methi Paratha": ["flour", "fenugreek", "onion", "garlic"],
  "Mango Rice": ["rice", "mango", "onion", "mustard"],
  "Pulao": ["rice", "onion", "carrot", "cumin"],
  "Tandoori Mushroom": ["mushrooms", "yogurt", "garlic", "chili powder"],
  "Aloo Gajar": ["potato", "carrot", "onion", "cumin"],
  "Pav Bhaji": ["bread", "potato", "onion", "tomato"],
  "Rajma": ["kidney beans", "onion", "tomato", "garlic"],
  "Tandoori Aloo": ["potato", "yogurt", "garlic", "chili powder"],
  "Paneer Pakora": ["paneer", "flour", "garlic", "chili powder"],
  "Vegetable Soup": ["carrot", "onion", "broccoli", "tomato"],
  "Methi Muthiya": ["fenugreek", "flour", "onion", "cumin"],
  "Spaghetti with Garlic Butter": ["spaghetti", "butter", "garlic", "parmesan", "black pepper"],
  "Mango Chicken Stir-Fry": ["chicken breast", "mango", "onion", "garlic", "soy sauce"],
  "Eggplant Parmesan": ["eggplant", "tomato", "cheddar", "parmesan", "olive oil"],
  "Potato and Cabbage Curry": ["potato", "cabbage", "onion", "garlic", "cumin"],
  "Lemon Garlic Prawns": ["prawns", "garlic", "lemon", "butter", "chili powder"],
  "Baked Chicken with Vegetables": ["chicken breast", "carrot", "potato", "onion", "olive oil"],
  "Cabbage and Carrot Stir-Fry": ["cabbage", "carrot", "onion", "garlic", "soy sauce"],
  "Vegetable Frittata": ["egg", "onion", "tomato", "bell pepper", "cheese"],
  "Broccoli and Cheese Casserole": ["broccoli", "cheddar", "milk", "butter", "onion"],
  "Lemon Honey Chicken": ["chicken breast", "lemon", "honey", "garlic", "olive oil"],
  "Cheddar Stuffed Potato Skins": ["potato", "cheddar", "onion", "butter", "garlic"],
  "Spinach and Cheese Stuffed Chicken": ["chicken breast", "spinach", "cheese", "garlic", "butter"],
  "Fried Fish Fillets": ["fish fillets", "flour", "garlic", "paprika", "salt"],
  "Eggplant Stir-Fry": ["eggplant", "garlic", "onion", "soy sauce", "chili powder"],
  "Beef Stir-Fry": ["beef", "onion", "bell pepper", "soy sauce", "garlic"],
  "Baked Salmon with Vegetables": ["salmon", "zucchini", "tomato", "garlic", "olive oil"],
  "Carrot and Potato Mash": ["carrot", "potato", "butter", "garlic", "milk"],
  "Mango Yogurt Smoothie": ["mango", "yogurt", "milk", "honey", "ice cream"],
  "Chicken and Broccoli Stir-Fry": ["chicken breast", "broccoli", "garlic", "soy sauce", "onion"],
  "Fried Eggs with Garlic Spinach": ["egg", "spinach", "garlic", "butter", "black pepper"],
  "Beef and Potato Curry": ["beef", "potato", "onion", "garlic", "cumin"],
  "Zucchini and Tomato Stir-Fry": ["zucchini", "tomato", "garlic", "onion", "olive oil"],
  "Pumpkin Soup": ["pumpkin", "onion", "garlic", "cream", "vegetable oil"],
  "Lemon Garlic Roasted Potatoes": ["potato", "lemon", "garlic", "olive oil", "oregano"],
  "Vegetable and Cheese Quesadilla": ["cheddar", "onion", "bell pepper", "flour", "tomato"],
  "Cucumber and Tomato Salad": ["cucumber", "tomato", "onion", "lemon juice", "parsley"],
  "Apple and Cinnamon Porridge": ["apple", "oats", "cinnamon", "milk", "honey"],
  "Chicken and Rice Pilaf": ["chicken breast", "rice", "onion", "garlic", "vegetable oil"],
  "Cauliflower and Potato Curry": ["cauliflower", "potato", "onion", "garlic", "cumin"],
  "Mango Salad": ["mango", "onion", "carrot", "lemon juice", "parsley"],
  "Baked Sweet Potato Fries": ["sweet potato", "olive oil", "paprika", "garlic", "oregano"],
  "Pasta Primavera": ["spaghetti", "tomato", "bell pepper", "onion", "garlic"],
  "Beef and Carrot Stew": ["beef", "carrot", "onion", "garlic", "vegetable oil"],
  "Mushroom and Spinach Pasta": ["spaghetti", "mushrooms", "spinach", "garlic", "parmesan"],
  "Stuffed Bell Peppers": ["bell pepper", "rice", "onion", "tomato", "cheddar"],
  "Chicken and Vegetable Curry": ["chicken breast", "carrot", "potato", "onion", "cumin"],
  "Tomato and Garlic Soup": ["tomato", "garlic", "onion", "cream", "cumin"],
  "Cheese and Spinach Stuffed Mushrooms": ["mushrooms", "spinach", "cream cheese", "garlic", "cheddar"],
  "Fried Rice": ["rice", "soy sauce", "onion", "egg", "carrot"],
  "Baked Cod with Vegetables": ["cod", "zucchini", "potato", "onion", "garlic"],
  "Garlic Parmesan Potatoes": ["potato", "garlic", "parmesan", "butter", "oregano"],
  "Sweet Potato and Spinach Stir-Fry": ["sweet potato", "spinach", "onion", "garlic", "olive oil"],
  "Pasta with Tuna": ["spaghetti", "tuna", "onion", "tomato", "olive oil"],
  "Pumpkin and Tomato Soup": ["pumpkin", "tomato", "onion", "garlic", "cream"],
  "Chicken and Potato Bake": ["chicken breast", "potato", "onion", "cheese", "garlic"],
  "Tomato Cucumber Salad": ["tomato", "cucumber", "onion", "lemon juice", "oregano"],
  "Mango and Shrimp Salad": ["mango", "shrimp", "onion", "garlic", "lime"],
  "Pumpkin Curry": ["pumpkin", "onion", "garlic", "cumin", "coconut milk"],
  "Vegetable Korma": ["carrot", "potato", "onion", "coconut milk", "garlic"],
  "Beef and Mushroom Stir-Fry": ["beef", "mushrooms", "soy sauce", "onion", "garlic"],
  "Lemon Chicken Stir-Fry": ["chicken breast", "lemon", "garlic", "onion", "soy sauce"],
  "Pineapple Fried Rice": ["pineapple", "rice", "onion", "garlic", "soy sauce"],
  "Sweet Potato and Kale Soup": ["sweet potato", "kale", "onion", "garlic", "cream"],
  "Broccoli and Potato Gratin": ["broccoli", "potato", "cheese", "cream", "garlic"],
  "Carrot and Ginger Soup": ["carrot", "ginger", "onion", "garlic", "cream"],
  "Apple Cinnamon Pancakes": ["apple", "flour", "cinnamon", "egg", "milk"],
  "Cheddar Stuffed Potatoes": ["potato", "cheddar", "butter", "onion", "garlic"],
  "Vegetable and Paneer Stir-Fry": ["paneer", "carrot", "bell pepper", "onion", "garlic"],
  "Cabbage and Potato Stew": ["cabbage", "potato", "onion", "garlic", "vegetable oil"],
  "Tomato and Basil Pasta": ["spaghetti", "tomato", "basil", "olive oil", "garlic"],
  "Vegetable Biryani": ["rice", "carrot", "peas", "onion", "garlic"],
  "Kale and Potato Soup": ["kale", "potato", "onion", "garlic", "cream"],
  "Roasted Garlic Potatoes": ["potato", "garlic", "olive oil", "paprika", "oregano"],
  "Grilled Chicken with Tomato Salad": ["chicken breast", "tomato", "onion", "garlic", "olive oil"],
  "Mushroom and Spinach Stir-Fry": ["mushrooms", "spinach", "onion", "garlic", "soy sauce"],
  "Lemon and Honey Chicken": ["chicken breast", "lemon", "honey", "garlic", "butter"],
  "Apple and Pear Salad": ["apple", "pear", "lemon juice", "onion", "parsley"],
  "Broccoli and Cheese Stuffed Chicken": ["chicken breast", "broccoli", "cheese", "garlic", "butter"],
  "Chicken and Sweet Potato Stew": ["chicken breast", "sweet potato", "onion", "garlic", "carrot"],
  "Crispy Potato Wedges": ["potato", "olive oil", "paprika", "garlic", "black pepper"],
  "Vegetable Pakoras": ["flour", "onion", "potato", "bell pepper", "cumin", "vegetable oil"],
  "Garlic Butter Mushrooms": ["butter", "garlic", "parsley", "onion powder"],
  "Parmesan Spaghetti": ["spaghetti", "parmesan", "olive oil", "basil"],
  "Crispy Onion Pakoras": ["onion", "flour", "cumin", "chili powder", "vegetable oil"],
  "Honey Cinnamon Pancakes": ["flour", "sugar", "milk", "honey", "cinnamon"],
  "Garlic Butter Naan": ["butter", "garlic", "flour", "milk", "sugar", "baking powder", "olive oil"],
  "Enhanced Egg Curry": ["egg", "onion", "garlic", "tomato", "cumin", "chili powder", "paprika"],
  "Pakistani Korma": ["chicken breast", "onion", "garlic", "yogurt", "cumin", "paprika", "cinnamon"],
  "Spiced Honey Glazed Carrots": ["carrot", "honey", "cinnamon", "butter"],
  "Garlic Fried Rice": ["white rice", "garlic", "vegetable oil", "soy sauce"],
  "Aloo Paratha": ["flour", "potato", "onion", "garlic powder", "cumin", "butter"],
  "Honey Chili Chicken": ["chicken breast", "honey", "chili powder", "garlic", "soy sauce"],
  "Spaghetti Garlic Butter": ["spaghetti", "butter", "garlic", "parsley", "parmesan"],
  "Vanilla Pancakes": ["flour", "sugar", "milk", "vanilla", "baking powder", "butter"],
   "Jaggery and Ghee Ladoo": ["jaggery", "ghee"],
  "Honey and Almond Halwa": ["honey", "almonds"],
  "Coconut Sugar Roti": ["coconut sugar", "flour"],
  "Maple Syrup Sweet Pongal": ["maple syrup", "rice"],
  "Jaggery and Coconut Barfi": ["jaggery", "coconut"],
  "Honey and Milk Pudding": ["honey", "milk", "cardamom"],
  "Coconut Sugar Puran Poli": ["coconut sugar", "flour", "turmeric"],
  "Maple Syrup Kheer": ["maple syrup", "rice", "milk"],
  "Jaggery and Sesame Chikki": ["jaggery", "sesame seeds", "ghee"],
  "Honey and Saffron Lassi": ["honey", "yogurt", "saffron"],
  "Gulab Jamun with Jaggery Syrup": ["jaggery", "flour", "milk powder", "ghee", "water", "rose water"],
  "Coconut Sugar Gajar Halwa": ["coconut sugar", "carrot", "milk", "ghee", "cardamom", "cashews"],
  "Maple Syrup Gajar Ka Halwa": ["maple syrup", "carrot", "milk", "ghee", "sugar", "cardamom"],
  "Jaggery and Coconut Payasam": ["jaggery", "coconut milk", "rice", "cashews", "raisins", "cardamom"],
  "Honey and Dates Pudding": ["honey", "dates", "milk", "ghee", "cardamom", "almonds"],
  "Jaggery and Milk Peda": ["jaggery", "milk"],
  "Honey and Ginger Chutney": ["honey", "ginger"],
  "Coconut Sugar Besan Ladoo": ["coconut sugar", "gram flour"],
  "Maple Syrup Malpua": ["maple syrup", "flour"],
  "Jaggery and Banana Halwa": ["jaggery", "banana"],
  "Honey and Cashew Halwa": ["honey", "cashews", "ghee"],
  "Coconut Sugar Kheer": ["coconut sugar", "rice", "milk"],
  "Jaggery and Moong Dal Laddu": ["jaggery", "moong dal", "ghee"],
  "Maple Syrup Coconut Ladoo": ["maple syrup", "coconut", "milk"],
  "Honey and Pistachio Barfi": ["honey", "pistachio", "milk"],
  "Jaggery Coconut Laddu": ["jaggery", "coconut", "ghee", "milk", "cardamom", "cashews"],
  "Coconut Sugar Kaju Katli": ["coconut sugar", "cashews", "ghee", "cardamom", "sugar", "water"],
  "Honey and Jaggery Lassi": ["honey", "jaggery", "yogurt", "milk", "cardamom", "saffron"],
  "Gajar Halwa with Maple Syrup": ["maple syrup", "carrot", "milk", "ghee", "cardamom", "cashews"],
  "Jaggery and Almond Burfi": ["jaggery", "almonds", "milk", "ghee", "cardamom", "sugar"]
};
      


export default Recipes
  